image: registry.gitlab.com/islandoftex/images/texlive:latest

variables:
  # tex file without .tex extensions
  MAIN_TEX_FILE: beleg

  # output file name without extension (.pdf)
  # e.g. "file" will result in "file.pdf"
  OUTPUT_FILE_NAME: Beleg

build:
  script:
    - pdflatex -synctex=1 -interaction=nonstopmode -shell-escape $MAIN_TEX_FILE
    - biber beleg
    - pdflatex -synctex=1 -interaction=nonstopmode -shell-escape $MAIN_TEX_FILE
  
  after_script:
    - cat $MAIN_TEX_FILE.log
    - mv $MAIN_TEX_FILE.pdf $OUTPUT_FILE_NAME.pdf
  
  artifacts:
    paths:
      - $OUTPUT_FILE_NAME.pdf

# https://gitlab.com/islandoftex/images/texlive/-/wikis/Compiling-LaTeX-documents-with-GitLab-CI
