image: registry.gitlab.com/islandoftex/images/texlive:latest

variables:
  # tex file without .tex extensions
  MAIN_TEX_FILE: 01_git-vorgehensmodelle

  # output file name without extension (.pdf)
  # e.g. "file" will result in "file.pdf"
  OUTPUT_FILE_NAME: 01-Git_Vorgehensmodelle

build:
  script:
    # find all cite commands, list in .aux, bib-style
    - pdflatex -synctex=1 -interaction=nonstopmode -shell-escape $MAIN_TEX_FILE.tex
    # create .bbl
    - bibtex $MAIN_TEX_FILE
    # read .bbl
    - pdflatex -synctex=1 -interaction=nonstopmode -shell-escape $MAIN_TEX_FILE.tex
    # resolve references
    - pdflatex -synctex=1 -interaction=nonstopmode -shell-escape $MAIN_TEX_FILE.tex
  
  after_script:
    - cat $MAIN_TEX_FILE.log
    - ls -lah
    - mv $MAIN_TEX_FILE.pdf $OUTPUT_FILE_NAME.pdf
  
  artifacts:
    paths:
      - $OUTPUT_FILE_NAME.pdf

# https://gitlab.com/islandoftex/images/texlive/-/wikis/Compiling-LaTeX-documents-with-GitLab-CI
