= Best Practises für Git-Vorgehensmodelle in größeren Teams

== Abstrakt

Die vorliegende Arbeit widmet sich verschiedenen Git-Vorgehensmodellen, die für Softwareentwicklungsprojekte in größeren Teams in Betracht kommen. Ziel ist es, ein grundlegendes Verständnis für die Anwendung dieser Strategien zu vermitteln.

Im ersten Teil der Arbeit werden die ausgewählten Git-Vorgehensmodelle im Einzelnen vorgestellt. Im Anschluss erfolgt eine Gegenüberstellung und Bewertung der verschiedenen Vorgehensmodelle anhand ausgewählter Kriterien. Dadurch sollen die Leser:innen in die Lage versetzt werden, die Stärken und Schwächen der verschiedenen Ansätze zu verstehen und entsprechende Entscheidungen für die Auswahl eines geeigneten Vorgehensmodells in Abhängigkeit von den Projektanforderungen zu treffen.

Die Arbeit kommt zur Erkenntnis, dass Gitflow und Trunk-based Development als Basis-Workflow für unterschiedliche Szenarien geeignet sind. Diese sollten jedoch an den entsprechenden Team- und Projektkontext angepasst werden. Für Open-Source-Projekte eignet sich zusätzlich der Forking-Workflow als übergeordnetes Vorgehensmodell.

== Kontext

[cols=2,1]
|===
| Titel
| Best Practices für Git-Vorgehensmodell in größeren Teams

| Autor:innen (alphabetisch)
| Nico Schramm, Johann Straube, Mirella Willems

| Beleg
| https://gitlab.dit.htwk-leipzig.de/23-swe-thema-1/abgabe/-/jobs/artifacts/main/raw/01-Git_Vorgehensmodelle.pdf?job=build[PDF-Version], link:01_git-vorgehensmodelle.tex[LaTeX-Datei]

| Präsentation
| link:presentation.pdf[PDF-Version]

| Kontext
| Modul “Software Engineering” (Prof. Dr. Andreas Both, Wintersemester 2023/2024) an der HTWK Leipzig

| Lizenz
| link:LICENSE[CC BY 4.0]

| Präsentationstermin
| 19. Dezember 2023
|===
